[phases.setup]
nixPkgs = ['nodejs', 'pnpm', 'python3']

[phases.install]
cmds = ['cd /app && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['cd /app/backend/gateway && pnpm build']

[start]
cmd = 'pnpm start'
